INSERT INTO currency(code,name) value("AED","United Arab Emirates Dirham"                                      );
INSERT INTO currency(code,name) value("AFN","Afghan Afghani"                                                   );
INSERT INTO currency(code,name) value("ALL","Albanian Lek"                                                     );
INSERT INTO currency(code,name) value("AMD","Armenian Dram"                                                    );
INSERT INTO currency(code,name) value("ANG","Netherlands Antillean Guilder"                                    );
INSERT INTO currency(code,name) value("AOA","Angolan Kwanza"                                                   );
INSERT INTO currency(code,name) value("ARS","Argentine Peso"                                                   );
INSERT INTO currency(code,name) value("AUD","Australian Dollar"                                                );
INSERT INTO currency(code,name) value("AWG","Aruban Florin"                                                    );
INSERT INTO currency(code,name) value("AZN","Azerbaijani Manat"                                                );
INSERT INTO currency(code,name) value("BAM","Bosnia-Herzegovina Convertible Mark"                              );
INSERT INTO currency(code,name) value("BBD","Barbadian Dollar"                                                 );
INSERT INTO currency(code,name) value("BDT","Bangladeshi Taka"                                                 );
INSERT INTO currency(code,name) value("BGN","Bulgarian Lev"                                                    );
INSERT INTO currency(code,name) value("BHD","Bahraini Dinar"                                                   );
INSERT INTO currency(code,name) value("BIF","Burundian Franc"                                                  );
INSERT INTO currency(code,name) value("BMD","Bermudan Dollar"                                                  );
INSERT INTO currency(code,name) value("BND","Brunei Dollar"                                                    );
INSERT INTO currency(code,name) value("BOB","Bolivian Boliviano"                                               );
INSERT INTO currency(code,name) value("BRL","Brazilian Real"                                                   );
INSERT INTO currency(code,name) value("BSD","Bahamian Dollar"                                                  );
INSERT INTO currency(code,name) value("BTC","Bitcoin"                                                          );
INSERT INTO currency(code,name) value("BTN","Bhutanese Ngultrum"                                               );
INSERT INTO currency(code,name) value("BWP","Botswanan Pula"                                                   );
INSERT INTO currency(code,name) value("BYR","Belarusian Ruble"                                                 );
INSERT INTO currency(code,name) value("BZD","Belize Dollar"                                                    );
INSERT INTO currency(code,name) value("CAD","Canadian Dollar"                                                  );
INSERT INTO currency(code,name) value("CDF","Congolese Franc"                                                  );
INSERT INTO currency(code,name) value("CHF","Swiss Franc"                                                      );
INSERT INTO currency(code,name) value("CLF","Chilean Unit of Account (UF)"                                     );
INSERT INTO currency(code,name) value("CLP","Chilean Peso"                                                     );
INSERT INTO currency(code,name) value("CNY","Chinese Yuan"                                                     );
INSERT INTO currency(code,name) value("COP","Colombian Peso"                                                   );
INSERT INTO currency(code,name) value("CRC","Costa Rican Col\u00f3n"                                           );
INSERT INTO currency(code,name) value("CUC","Cuban Convertible Peso"                                           );
INSERT INTO currency(code,name) value("CUP","Cuban Peso"                                                       );
INSERT INTO currency(code,name) value("CVE","Cape Verdean Escudo"                                              );
INSERT INTO currency(code,name) value("CZK","Czech Republic Koruna"                                            );
INSERT INTO currency(code,name) value("DJF","Djiboutian Franc"                                                 );
INSERT INTO currency(code,name) value("DKK","Danish Krone"                                                     );
INSERT INTO currency(code,name) value("DOP","Dominican Peso"                                                   );
INSERT INTO currency(code,name) value("DZD","Algerian Dinar"                                                   );
INSERT INTO currency(code,name) value("EEK","Estonian Kroon"                                                   );
INSERT INTO currency(code,name) value("EGP","Egyptian Pound"                                                   );
INSERT INTO currency(code,name) value("ERN","Eritrean Nakfa"                                                   );
INSERT INTO currency(code,name) value("ETB","Ethiopian Birr"                                                   );
INSERT INTO currency(code,name) value("EUR","Euro"                                                             );
INSERT INTO currency(code,name) value("FJD","Fijian Dollar"                                                    );
INSERT INTO currency(code,name) value("FKP","Falkland Islands Pound"                                           );
INSERT INTO currency(code,name) value("GBP","British Pound Sterling"                                           );
INSERT INTO currency(code,name) value("GEL","Georgian Lari"                                                    );
INSERT INTO currency(code,name) value("GGP","Guernsey Pound"                                                   );
INSERT INTO currency(code,name) value("GHS","Ghanaian Cedi"                                                    );
INSERT INTO currency(code,name) value("GIP","Gibraltar Pound"                                                  );
INSERT INTO currency(code,name) value("GMD","Gambian Dalasi"                                                   );
INSERT INTO currency(code,name) value("GNF","Guinean Franc"                                                    );
INSERT INTO currency(code,name) value("GTQ","Guatemalan Quetzal"                                               );
INSERT INTO currency(code,name) value("GYD","Guyanaese Dollar"                                                 );
INSERT INTO currency(code,name) value("HKD","Hong Kong Dollar"                                                 );
INSERT INTO currency(code,name) value("HNL","Honduran Lempira"                                                 );
INSERT INTO currency(code,name) value("HRK","Croatian Kuna"                                                    );
INSERT INTO currency(code,name) value("HTG","Haitian Gourde"                                                   );
INSERT INTO currency(code,name) value("HUF","Hungarian Forint"                                                 );
INSERT INTO currency(code,name) value("IDR","Indonesian Rupiah"                                                );
INSERT INTO currency(code,name) value("ILS","Israeli New Sheqel"                                               );
INSERT INTO currency(code,name) value("IMP","Manx pound"                                                       );
INSERT INTO currency(code,name) value("INR","Indian Rupee"                                                     );
INSERT INTO currency(code,name) value("IQD","Iraqi Dinar"                                                      );
INSERT INTO currency(code,name) value("IRR","Iranian Rial"                                                     );
INSERT INTO currency(code,name) value("ISK","Icelandic Kr\u00f3na"                                             );
INSERT INTO currency(code,name) value("JEP","Jersey Pound"                                                     );
INSERT INTO currency(code,name) value("JMD","Jamaican Dollar"                                                  );
INSERT INTO currency(code,name) value("JOD","Jordanian Dinar"                                                  );
INSERT INTO currency(code,name) value("JPY","Japanese Yen"                                                     );
INSERT INTO currency(code,name) value("KES","Kenyan Shilling"                                                  );
INSERT INTO currency(code,name) value("KGS","Kyrgystani Som"                                                   );
INSERT INTO currency(code,name) value("KHR","Cambodian Riel"                                                   );
INSERT INTO currency(code,name) value("KMF","Comorian Franc"                                                   );
INSERT INTO currency(code,name) value("KPW","North Korean Won"                                                 );
INSERT INTO currency(code,name) value("KRW","South Korean Won"                                                 );
INSERT INTO currency(code,name) value("KWD","Kuwaiti Dinar"                                                    );
INSERT INTO currency(code,name) value("KYD","Cayman Islands Dollar"                                            );
INSERT INTO currency(code,name) value("KZT","Kazakhstani Tenge"                                                );
INSERT INTO currency(code,name) value("LAK","Laotian Kip"                                                      );
INSERT INTO currency(code,name) value("LBP","Lebanese Pound"                                                   );
INSERT INTO currency(code,name) value("LKR","Sri Lankan Rupee"                                                 );
INSERT INTO currency(code,name) value("LRD","Liberian Dollar"                                                  );
INSERT INTO currency(code,name) value("LSL","Lesotho Loti"                                                     );
INSERT INTO currency(code,name) value("LTL","Lithuanian Litas"                                                 );
INSERT INTO currency(code,name) value("LVL","Latvian Lats"                                                     );
INSERT INTO currency(code,name) value("LYD","Libyan Dinar"                                                     );
INSERT INTO currency(code,name) value("MAD","Moroccan Dirham"                                                  );
INSERT INTO currency(code,name) value("MDL","Moldovan Leu"                                                     );
INSERT INTO currency(code,name) value("MGA","Malagasy Ariary"                                                  );
INSERT INTO currency(code,name) value("MKD","Macedonian Denar"                                                 );
INSERT INTO currency(code,name) value("MMK","Myanma Kyat"                                                      );
INSERT INTO currency(code,name) value("MNT","Mongolian Tugrik"                                                 );
INSERT INTO currency(code,name) value("MOP","Macanese Pataca"                                                  );
INSERT INTO currency(code,name) value("MRO","Mauritanian Ouguiya"                                              );
INSERT INTO currency(code,name) value("MTL","Maltese Lira"                                                     );
INSERT INTO currency(code,name) value("MUR","Mauritian Rupee"                                                  );
INSERT INTO currency(code,name) value("MVR","Maldivian Rufiyaa"                                                );
INSERT INTO currency(code,name) value("MWK","Malawian Kwacha"                                                  );
INSERT INTO currency(code,name) value("MXN","Mexican Peso"                                                     );
INSERT INTO currency(code,name) value("MYR","Malaysian Ringgit"                                                );
INSERT INTO currency(code,name) value("MZN","Mozambican Metical"                                               );
INSERT INTO currency(code,name) value("NAD","Namibian Dollar"                                                  );
INSERT INTO currency(code,name) value("NGN","Nigerian Naira"                                                   );
INSERT INTO currency(code,name) value("NIO","Nicaraguan C\u00f3rdoba"                                          );
INSERT INTO currency(code,name) value("NOK","Norwegian Krone"                                                  );
INSERT INTO currency(code,name) value("NPR","Nepalese Rupee"                                                   );
INSERT INTO currency(code,name) value("NZD","New Zealand Dollar"                                               );
INSERT INTO currency(code,name) value("OMR","Omani Rial"                                                       );
INSERT INTO currency(code,name) value("PAB","Panamanian Balboa"                                                );
INSERT INTO currency(code,name) value("PEN","Peruvian Nuevo Sol"                                               );
INSERT INTO currency(code,name) value("PGK","Papua New Guinean Kina"                                           );
INSERT INTO currency(code,name) value("PHP","Philippine Peso"                                                  );
INSERT INTO currency(code,name) value("PKR","Pakistani Rupee"                                                  );
INSERT INTO currency(code,name) value("PLN","Polish Zloty"                                                     );
INSERT INTO currency(code,name) value("PYG","Paraguayan Guarani"                                               );
INSERT INTO currency(code,name) value("QAR","Qatari Rial"                                                      );
INSERT INTO currency(code,name) value("RON","Romanian Leu"                                                     );
INSERT INTO currency(code,name) value("RSD","Serbian Dinar"                                                    );
INSERT INTO currency(code,name) value("RUB","Russian Ruble"                                                    );
INSERT INTO currency(code,name) value("RWF","Rwandan Franc"                                                    );
INSERT INTO currency(code,name) value("SAR","Saudi Riyal"                                                      );
INSERT INTO currency(code,name) value("SBD","Solomon Islands Dollar"                                           );
INSERT INTO currency(code,name) value("SCR","Seychellois Rupee"                                                );
INSERT INTO currency(code,name) value("SDG","Sudanese Pound"                                                   );
INSERT INTO currency(code,name) value("SEK","Swedish Krona"                                                    );
INSERT INTO currency(code,name) value("SGD","Singapore Dollar"                                                 );
INSERT INTO currency(code,name) value("SHP","Saint Helena Pound"                                               );
INSERT INTO currency(code,name) value("SLL","Sierra Leonean Leone"                                             );
INSERT INTO currency(code,name) value("SOS","Somali Shilling"                                                  );
INSERT INTO currency(code,name) value("SRD","Surinamese Dollar"                                                );
INSERT INTO currency(code,name) value("STD","S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra"                       );
INSERT INTO currency(code,name) value("SVC","Salvadoran Col\u00f3n"                                            );
INSERT INTO currency(code,name) value("SYP","Syrian Pound"                                                     );
INSERT INTO currency(code,name) value("SZL","Swazi Lilangeni"                                                  );
INSERT INTO currency(code,name) value("THB","Thai Baht"                                                        );
INSERT INTO currency(code,name) value("TJS","Tajikistani Somoni"                                               );
INSERT INTO currency(code,name) value("TMT","Turkmenistani Manat"                                              );
INSERT INTO currency(code,name) value("TND","Tunisian Dinar"                                                   );
INSERT INTO currency(code,name) value("TOP","Tongan Pa\u02bbanga"                                              );
INSERT INTO currency(code,name) value("TRY","Turkish Lira"                                                     );
INSERT INTO currency(code,name) value("TTD","Trinidad and Tobago Dollar"                                       );
INSERT INTO currency(code,name) value("TWD","New Taiwan Dollar"                                                );
INSERT INTO currency(code,name) value("TZS","Tanzanian Shilling"                                               );
INSERT INTO currency(code,name) value("UAH","Ukrainian Hryvnia"                                                );
INSERT INTO currency(code,name) value("UGX","Ugandan Shilling"                                                 );
INSERT INTO currency(code,name) value("USD","United States Dollar"                                             );
INSERT INTO currency(code,name) value("UYU","Uruguayan Peso"                                                   );
INSERT INTO currency(code,name) value("UZS","Uzbekistan Som"                                                   );
INSERT INTO currency(code,name) value("VEF","Venezuelan Bol\u00edvar Fuerte"                                   );
INSERT INTO currency(code,name) value("VND","Vietnamese Dong"                                                  );
INSERT INTO currency(code,name) value("VUV","Vanuatu Vatu"                                                     );
INSERT INTO currency(code,name) value("WST","Samoan Tala"                                                      );
INSERT INTO currency(code,name) value("XAF","CFA Franc BEAC"                                                   );
INSERT INTO currency(code,name) value("XAG","Silver (troy ounce)"                                              );
INSERT INTO currency(code,name) value("XAU","Gold (troy ounce)"                                                );
INSERT INTO currency(code,name) value("XCD","East Caribbean Dollar"                                            );
INSERT INTO currency(code,name) value("XDR","Special Drawing Rights"                                           );
INSERT INTO currency(code,name) value("XOF","CFA Franc BCEAO"                                                  );
INSERT INTO currency(code,name) value("XPD","Palladium Ounce"                                                  );
INSERT INTO currency(code,name) value("XPF","CFP Franc"                                                        );
INSERT INTO currency(code,name) value("XPT","Platinum Ounce"                                                   );
INSERT INTO currency(code,name) value("YER","Yemeni Rial"                                                      );
INSERT INTO currency(code,name) value("ZAR","South African Rand"                                               );
INSERT INTO currency(code,name) value("ZMK","Zambian Kwacha (pre-2013)"                                        );
INSERT INTO currency(code,name) value("ZMW","Zambian Kwacha"                                                   );
INSERT INTO currency(code,name) value("ZWL","Zimbabwean Dollar"                                                );